spring.application.name=srms
spring.data.mongodb.uri=mongodb+srv://SRMS:Sakec4321@cluster0.grn9igb.mongodb.net/?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true

server.port=5000

# JWT secret key (must be the same as in Node.js)
jwt.secret=sEcReT
# Should be in milliseconds (1 hour)
jwt.expiration=3600000

# CORS Configuration
cors.allowed-origins=*
